version: '3.8'

services:
  game-ia-web:
    build: .
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.game-ia.rule=Host(`game-ia.localhost`)"
      - "traefik.http.services.game-ia.loadbalancer.server.port=80"

networks:
  default:
    driver: bridge